ADMIN = 'admin'
MODERATOR = 'moderator'
USER = 'user'
TRUNCATED_MODEL_NAME = 25
MAX_REVIEW_CHARACTERS = 500
MAX_COMMENT_CHARACTERS = 200

MAX_CODE_CHARACTERS = 256
MAX_USERNAME_CHARACTERS = 150
MAX_EMAIL_CHARACTERS = 254
