ADMIN = 'admin'
MODERATOR = 'moderator'
USER = 'user'
USERNAME_ME = 'me'
REGEX_USERNAME = r'^[\w.@+-]+\Z'
TRUNCATED_MODEL_NAME = 25
MAX_NAME_CHARS = 256
MAX_SLUG_CHARS = 50
MAX_SCORE_VALUE = 10
MIN_SCORE_VALUE = 1

MAX_CODE_CHARACTERS = 256
MAX_USERNAME_CHARACTERS = 150
MAX_EMAIL_CHARACTERS = 254
