# Generated by Django 3.2 on 2023-11-08 12:10

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже есть'}, help_text='Обязательное поле. Не более 150 символов. Только буквы и цифры, символы @+-', max_length=150, unique=True, validators=[users.models.validate_username, django.core.validators.RegexValidator('^[\\w.@+-]+\\Z', 'Используются недопустимые символы')], verbose_name='Логин'),
        ),
    ]
