# Generated by Django 3.2 on 2023-11-13 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231112_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Введите оценку от 1 до 10'), django.core.validators.MinValueValidator(1, message='Введите оценку от 1 до 10')], verbose_name='Оценка'),
        ),
    ]
