# Generated by Django 3.2 on 2023-11-13 08:43

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231112_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[reviews.validators.validate_score], verbose_name='Оценка'),
        ),
    ]
